Notes:

// MIDI - SC makes two more ports than necessary... this should be fixed! (system announce and system timer)

// MIDIOut
// disconnect should not need to know what to disconnect, or?

// newByName does not work on Linux (fix in docs, or in code)

// MIDIFunc : add trace for sysrt, sysex, etc. and add convenience methods for these.


// MTC to main library?

// OSC:
// should there also be a way to send messages *from* a specific port?